---
deployment:
  tasks:
    # unnifidata.com
    - export DEPLOYPATH=/home/eamkwr6qtvau/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp products.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp 404page.html $DEPLOYPATH
    - /bin/cp termsandconditions.html $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH