---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/unnifidata.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp products.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp 404page.html $DEPLOYPATH
    - /bin/cp t&c.html $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH